application: helloworld201304
version: 9
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: 2.6
  
handlers:
- url: /.*
  script: helloworld.app

- url: /stylesheets
  static_dir: stylesheets
  
